{% set name = "xpublish" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb31b2937a80f607dd7d1e5739a5137ca7ed6de5211fe3ec9c1ded0d89b3486a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - xarray >=0.16
    - dask
    - toolz
    - zarr
    - numcodecs
    - fastapi >=0.59
    - uvicorn

test:
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - xpublish

about:
  home: https://xpublish.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Publish Xarray Datasets via a Zarr compatible REST API
  description: |
    Xpublish lets you serve, share and publish Xarray Datasets via a web application.
    The data and/or metadata in the Xarray Datasets can be exposed in various forms
    through pluggable REST API endpoints. Efficient, on-demand delivery of large
    datasets may be enabled with Dask on the server-side.
  doc_url: https://xpublish.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/xpublish
extra:
  recipe-maintainers:
    - jhamman
    - andersy005
