{% set name = "xpublish" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0707933f0034f208639d0abd3a9b55ad44e70c4fc85091db9d4468ad58721a2e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - xarray
    - dask
    - toolz
    - zarr
    - numcodecs
    - fastapi
    - uvicorn

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - xpublish

about:
  home: https://github.com/jhamman/xarray
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Publish Xarray Datasets via a Zarr compatible REST API
  description: |
    Xpublish lets you publish Xarray datasets via a Zarr-compatible REST API.
    On the server-side, datasets are published using a simple Xarray accessor
    and on the client-side, datasets are accessed using Zarr and fsspec.
  doc_url: https://xpublish.readthedocs.io/
  dev_url: https://github.com/jhamman/xpublish
extra:
  recipe-maintainers:
    - jhamman
    - andersy005
